### ISSUE TITLE
Upload .zip or .tar of ImageNet-G-1k to google drive

### ISSUE THREAD

**Issue by rtaori** [Hritikbansal/generative-robustness#1]
Hi,

I am having some issues downloading the dataset from google drive - since the dataset is quite large / contains many files, the server doesn't seem to zip the files properly for download and so the entire dataset isn't downloaded. Would it be possible to .zip or .tar the entire folder and then upload to drive as one file? It would make it a lot easier to download.

Thanks!

**Comment by Hritikbansal** [comment]
Hi,

I checked and the generated training data has not completely transferred from the server to the gdrive. It might take another week. I can give you an update as soon as it is complete. As you pointed out, the dataset is quite large which is taking sometime.

However, the generated validation data has completely transferred. Let me know if you are facing any issues with it.

**Comment by rtaori** [comment]
Ah that explains it. Yes, please let me know when it has finished transferring!

**Comment by rtaori** [comment]
Also, given how much I actually downloaded and how much is still left to upload, please consider uploading a single zip/tar file. It would make the downloading process much easier.

**Comment by Hritikbansal** [comment]
That’s a good suggestion! I will work on it and keep you posted on the transfer process for the training data.

**Comment by Hritikbansal** [comment]
I have started the process of uploading a single tar file for the training data. Will keep you posted as soon as it completes. Thanks!

**Comment by Hritikbansal** [comment]
@rtaori, the upload is complete. You should be able to download a `train.tar` file. Please let me know if you see the complete data now with ~1.28M examples.

**Comment by rtaori** [comment]
Yup it worked great, thanks
